#Makefile for PEtot on franklin 

FC=ftn
LDR=ftn
FFLAGS = -fast 
LIB = -lacml


system_scfft.o: system_scfft.f
	$(FC) $(FFLAGS) -o system_scfft.o -c $<

system_csfft.o: system_csfft.f
	$(FC) $(FFLAGS) -o system_csfft.o -c $<

system_ccfft.o: system_ccfft.f
	$(FC) $(FFLAGS) -o system_ccfft.o -c $<

SRC_obj=\
system_ccfft.o\
system_csfft.o\
system_scfft.o
