#Makefile for PEtot on IBM Power CPU using PGI compiler

FC=mpif90
LDR=mpif90
FFLAGS = -fast
F90FLAGS = $(FFLAGS)
LIB = -L${OLCF_ESSL_ROOT}/lib64 -lessl

system_scfft.o: system_scfft.ibm.f
	$(FC) $(FFLAGS) -o system_scfft.o -c $<

system_csfft.o: system_csfft.ibm.f
	$(FC) $(FFLAGS) -o system_csfft.o -c $<

system_ccfft.o: system_ccfft.ibm.f
	$(FC) $(FFLAGS) -o system_ccfft.o -c $<

SRC_obj=\
system_ccfft.o\
system_csfft.o\
system_scfft.o
